server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChristianStier/spring-petclinic-microservices-config
          # Uncomment for local configuration repository:
          # uri: file:///${GIT_REPO}

    